version: "3.7"
services:
    api:
        ports:
            - '80:80/tcp'
        image: 'metro-api-v2'
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            FTP_SERVER: ${FTP_SERVER}
            FTP_USERNAME: ${FTP_USERNAME}
            FTP_PASS: ${FTP_PASS}